version: "3.7"

volumes:
  boilerplatevolume:
    name: boilerplate-volume

networks:
  boilerplatenetwork:
    name: boilerplate-network

services:
  postgres:
    image: postgres:13
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - boilerplatevolume:/var/lib/postgresql/data
      - ./internal/db/scripts:/docker-entrypoint-initdb.d/
    networks:
      - boilerplatenetwork

  boilerplate_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        API_PORT: ${API_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - boilerplatenetwork
    entrypoint: [ "/bin/bash", "./scripts/entrypoint.dev.sh" ]