version: "3.7"

volumes:
  boilerplatevolume:
    name: boilerplate-volume

networks:
  boilerplatenetwork:
    name: boilerplate-network

services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - boilerplatevolume:/data
    networks:
      - boilerplatenetwork

  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=boilerplate
    ports:
      - "5432:5432"
    volumes:
      - boilerplatevolume:/var/lib/postgresql/data
      - ./internal/store/scripts:/docker-entrypoint-initdb.d/
    networks:
      - boilerplatenetwork

  boilerplate_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        API_PORT: "8080"
    env_file:
      - ./configs/app.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      - boilerplatenetwork
    entrypoint: [ "/bin/bash", "./scripts/entrypoint.dev.sh" ]